name: Ionic CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Cordova & Ionic
        run: sudo npm i -g cordova @ionic/cli
      - name: Build Android with Ionic
        run: |
          #TODO: cache npm modules
          npm install
          sudo ionic cordova build android
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: app-debug
          path: ./platforms/android/app/build/outputs/apk/debug/app-debug.apk
